Change CI/CD so dev and staging servers pull images from docker hub

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,13 +1,12 @@
 stages:
   - build
+  - build-docker
   - deploy
 
 variables:
   DEV_BRANCH: "master"
   STG_BRANCH: "staging"
   PROD_BRANCH: "production"
-  IMAGE_BACKEND: "baytree_server"
-  IMAGE_FRONTEND: "baytree_revproxy_frontend"
 
 build info:
   # Always runs: allows pipeline execution to happen even if no other tasks run.
@@ -88,7 +87,6 @@ build server:
       alias: test_mysql
   tags:
     - docker
-  needs: []
   rules:
     - if: "$CI_MERGE_REQUEST_ID != null"
       changes:
@@ -120,13 +118,89 @@ build server:
     - python manage.py check
     - python manage.py makemigrations --check
 
-.deploy-script: &deploy-script
+.deploy-script: &export_image_tag
+  # Set IMAGE_TAG to encode the date and SHA of the most recent commit.
+  - export IMAGE_TAG=v$(git show -s --format=%cs $CI_COMMIT_SHA).`git rev-parse --short=8 $CI_COMMIT_SHA`
+  # Display some useful info for understanding / debugging the pipeline
+  - echo "Docker hub user ='$HUB_USER',     version='$IMAGE_TAG'"
+  - echo "Full tag (backend) is               = $HUB_USER/$HUB_REPO_BACKEND:$IMAGE_TAG"
+  - echo "Full tag (rev-proxy & frontend) is  = $HUB_USER/$HUB_REPO_FRONTEND:$IMAGE_TAG"
+  - docker images
+
+
+build-docker publish-docker-images:
+  stage: build-docker
+  tags:
+    # Run on CI/CD server so it does not interfere with containers in active use on dev server.
+    - deploy-dockerhub-shell
+  rules:
+    - if: "$CI_COMMIT_BRANCH == $DEV_BRANCH"
+  script:
+    # Required environment variables defined by GitLab's settings:
+    #   HUB_USER:           Docker Hub user
+    #   HUB_TOKEN:          Docker Hub token
+    #   HUB_REPO_BACKEND:   Docker Hub project name for backend
+    #   HUB_REPO_FRONTEND:  Docker Hub project name for frontend / caddy
+
+    # Build images (tagged by docker-composition*.yml using IMAGE_TAG)
+    - *export_image_tag
+    - docker-compose -f docker-compose.yml -f docker-compose.deploy.yml build
+    
+    # Push images to Docker Hub 
+    - docker images
+    - docker login -u $HUB_USER -p $HUB_TOKEN
+    - docker push $HUB_USER/$HUB_REPO_BACKEND:$IMAGE_TAG
+    - docker push $HUB_USER/$HUB_REPO_FRONTEND:$IMAGE_TAG
+    - docker logout
+
+    # Cleanup the image and any tags of that image
+    # Run on the CI/CD server, so it can force delete these images because it does not run any of them as containers
+    - docker images -a | grep -e "$HUB_REPO_BACKEND" -e "$HUB_REPO_FRONTEND" | awk '{print $3}' | xargs docker rmi --force
+    - docker images
+
+
+.deploy-script: &deploy-from-dockerhub
+  - *export_image_tag
   - cp /var/baytree/.env ./.env
-  - docker-compose -f docker-compose.yml -f docker-compose.deploy.yml build
-  - docker-compose -f docker-compose.yml -f docker-compose.deploy.yml up --force-recreate -d
-  - docker image prune -f      # remove unused images since we just built new ones
+  - docker-compose -f docker-compose.yml -f docker-compose.deploy.yml pull
+  - docker-compose -f docker-compose.yml -f docker-compose.deploy.yml up -d
+  - docker image prune -f      # remove unused images since we just downloaded new ones
   - bash -c 'sleep 15'
   - docker exec baytree_server python manage.py migrate
+  - docker images
+
+.deploy-script: &retag-and-upload-dockerhub
+  # Required environment variables passed into this function:
+  #   BRANCH_TAG:         Determined by which branch we are building off: "dev", "staging", "prod"
+  - *export_image_tag
+
+  # Download images (docker skips if already be present)
+  - echo "Trying to tag images of version '$IMAGE_TAG' with new tag '$BRANCH_TAG'"
+  - | 
+    echo "If you get 'Error response from daemon - manifest for ... not found - manifest unknown - manifest unknown'"
+    echo "   it likely means the pipeline did not build and deploy a docker image for this commit."
+    echo "   Was there a MR to this branch that did not get build for use on Dev server?"
+  - echo "Downloading image = $HUB_USER/$HUB_REPO_BACKEND, tag = $IMAGE_TAG'..."
+  - docker pull $HUB_USER/$HUB_REPO_BACKEND:$IMAGE_TAG
+  - docker pull $HUB_USER/$HUB_REPO_FRONTEND:$IMAGE_TAG
+
+  # Retag
+  - docker tag $HUB_USER/$HUB_REPO_BACKEND:$IMAGE_TAG   $HUB_USER/$HUB_REPO_BACKEND:$BRANCH_TAG
+  - docker tag $HUB_USER/$HUB_REPO_FRONTEND:$IMAGE_TAG  $HUB_USER/$HUB_REPO_FRONTEND:$BRANCH_TAG
+
+  # Upload tags
+  - docker images
+  - docker login -u $HUB_USER -p $HUB_TOKEN
+  - docker push $HUB_USER/$HUB_REPO_BACKEND:$BRANCH_TAG
+  - docker push $HUB_USER/$HUB_REPO_FRONTEND:$BRANCH_TAG
+  - docker logout
+
+  # Cleanup (if in use as a container this will fail, so we tolerate failures)
+  - docker rmi $HUB_USER/$HUB_REPO_BACKEND:$BRANCH_TAG || true
+  - docker rmi $HUB_USER/$HUB_REPO_FRONTEND:$BRANCH_TAG || true
+  - docker rmi $HUB_USER/$HUB_REPO_BACKEND:$IMAGE_TAG || true
+  - docker rmi $HUB_USER/$HUB_REPO_FRONTEND:$IMAGE_TAG || true
+  - docker images
 
 deploy development:
   stage: deploy
@@ -135,11 +209,14 @@ deploy development:
     url: https://baytree-dev.cmpt.sfu.ca
   tags:
     - deploy-development
+  variables:
+    BRANCH_TAG: "dev"
   rules:
     - if: "$CI_COMMIT_BRANCH == $DEV_BRANCH"
-      when: on_success
   script:
-    - *deploy-script
+    # After images are built, deploy to dev-server & tag with "dev"
+    - *deploy-from-dockerhub
+    - *retag-and-upload-dockerhub
 
 deploy staging:
   stage: deploy
@@ -148,46 +225,22 @@ deploy staging:
     url: https://baytree-stg.cmpt.sfu.ca
   tags:
     - deploy-staging
+  variables:
+    BRANCH_TAG: "staging"
   rules:
     - if: "$CI_COMMIT_BRANCH == $STG_BRANCH"
-      when: on_success
   script:
-    - *deploy-script
+    - *deploy-from-dockerhub
+    - *retag-and-upload-dockerhub
 
-deploy dockerhub:
-  variables:
-    # The following are expected to be defined by GitLab's settings
-    #   Docker hub user & token: HUB_USER, HUB_TOKEN
-    #   Docker hub projects:     HUB_REPO_FRONTEND, HUB_REPO_BACKEND
+deploy production:
   stage: deploy
   tags:
     - deploy-dockerhub-shell
+  variables:
+    BRANCH_TAG: "prod"
   rules:
     - if: "$CI_COMMIT_BRANCH == $PROD_BRANCH"
-      when: manual
   script:
-    # Version of the form v2022-12-31.abcd5678, based on date and short SHA1 of last commit on branch
-    - export VERSION=v$(git show -s --format=%cs $CI_COMMIT_SHA).`git rev-parse --short=8 $CI_COMMIT_SHA`
-    # Show what we are expecting to build / tag
-    - echo "Docker Hub configuration       user ='$HUB_USER'     version='$VERSION'"
-    - echo "Full tag (backend) is               = $HUB_USER/$HUB_REPO_BACKEND:$VERSION (& ':latest')"
-    - echo "Full tag (rev-proxy & frontend) is  = $HUB_USER/$HUB_REPO_FRONTEND:$VERSION (& ':latest')"
-
-    # Build and tag
-    - docker-compose -f docker-compose.yml -f docker-compose.deploy.yml build
-    - docker tag $IMAGE_BACKEND $HUB_USER/$HUB_REPO_BACKEND:latest
-    - docker tag $IMAGE_BACKEND $HUB_USER/$HUB_REPO_BACKEND:$VERSION
-
-    - docker tag $IMAGE_FRONTEND $HUB_USER/$HUB_REPO_FRONTEND:latest
-    - docker tag $IMAGE_FRONTEND $HUB_USER/$HUB_REPO_FRONTEND:$VERSION
-
-    # Push images to Docker Hub with the latest and version tags
-    - docker images
-    - docker login -u $HUB_USER -p $HUB_TOKEN
-    - docker push --all-tags $HUB_USER/$HUB_REPO_BACKEND
-    - docker push --all-tags $HUB_USER/$HUB_REPO_FRONTEND
-    - docker logout
-
-    # Cleanup the image and any tags of that image
-    - docker images -a | grep -e "$IMAGE_BACKEND" -e "$IMAGE_FRONTEND" | awk '{print $3}' | xargs docker rmi --force
-    - docker images
+    - *retag-and-upload-dockerhub
+    # Production server's admin must manually log into the server and run the /root/update.sh script
